export const LANGUAGE_OPTIONS = [
  { id: "uk", shortLabel: "UA" },
  { id: "en", shortLabel: "EN" },
];

export const THEME_OPTIONS = [
  { id: "light", shortLabel: "Light" },
  { id: "dark", shortLabel: "Dark" },
];

const createCopy = (dictionary) => ({
  ...dictionary,
  levelLabel: (level) => `${dictionary.levelWord} ${level}`,
  nodeCountLabel: (count) => `${count} ${dictionary.nodesWord}`,
  relationCountLabel: (count) => `${count} ${dictionary.relationsWord}`,
  zoomLabel: (zoom) => `${dictionary.zoomWord} ${Math.round(zoom * 100)}%`,
});

export const UI_COPY = {
  uk: createCopy({
    navEyebrow: "Навігація",
    appTitle: "Карта країни",
    pageSwitchAria: "Екрани застосунку",
    pageSwitchLabel: "Сторінка",
    themeSwitchLabel: "Тема",
    languageSwitchLabel: "Мова",
    lightTheme: "Світла",
    darkTheme: "Темна",
    listTab: "Список",
    mindMapTab: "Мапа",
    projectEyebrow: "Проєкт",
    loadingTitle: "Завантажуємо карту",
    loadingDescription:
      "Готуємо структуру, щоб можна було перейти до списку та візуальної карти.",
    errorTitle: "Не вдалося відкрити карту",
    errorDescription: "Дані не знайдено.",
    aboutProject: "Про проєкт",
    heroTitle: "Карта структури країни",
    heroText:
      "Цей проєкт допомагає швидко орієнтуватися в установах, їхніх ролях і зв'язках між собою. Тут можна знайти потрібний вузол, подивитися його місце в ієрархії та перейти до візуальної карти взаємодій.",
    searchPlaceholder: "Пошук",
    searchResultsAria: "Результати пошуку",
    nothingFound: "Нічого не знайдено.",
    structureEyebrow: "Структура",
    hierarchyTitle: "Ієрархія",
    expandAll: "Розгорнути все",
    collapseAll: "Згорнути",
    tryAnotherQuery: "Нічого не знайдено. Спробуйте інший запит.",
    nodeCardEyebrow: "Картка вузла",
    breadcrumbAria: "Навігаційний ланцюжок",
    whatIsThis: "Що це",
    directChildren: "Прямі нижчі вузли",
    noChildren: "На цьому вузлі нижчих елементів зараз немає.",
    explanationEyebrow: "Пояснення",
    howToReadArrows: "Як читати стрілочки",
    helpTextOne: "Стрілка показує напрямок взаємодії між двома вузлами.",
    helpTextTwo:
      "Колір і стиль лінії підказують тип зв'язку: підпорядкування, координація, нагляд, сервіс або правова основа.",
    helpTextThree:
      "Натисніть на стрілку, щоб побачити її пояснення та джерела для перевірки.",
    nodesTitle: "Вузли",
    nodesText: "Елементи, які відображені на мапі.",
    relationsTitle: "Зв'язки",
    relationsText: "Стрілки між вузлами на полотні.",
    activeNodeTitle: "Активний вузол",
    activeNodeText: "Поточний вибраний елемент.",
    levelWord: "Рівень",
    nodesWord: "вузлів",
    relationsWord: "зв'язків",
    zoomWord: "Масштаб",
    levelOverviewText: "Ключові об'єкти цього рівня у загальній структурі.",
    mindMapEyebrow: "Мапа взаємодій",
    globalMindMap: "Глобальна мапа",
    zoomOut: "Зменшити масштаб",
    zoomIn: "Збільшити масштаб",
    enterFullscreen: "Повноекранний режим",
    exitFullscreen: "Вийти з повноекранного режиму",
    focusActiveNode: "До активного вузла",
    relationDetailsEyebrow: "Деталі зв'язку",
    pickRelation: "Оберіть зв'язок",
    activeNodeRelations: "Зв'язки активного вузла",
    noVisibleRelations: "Для активного вузла поки немає видимих зв'язків на мапі.",
    relationDescription: "Опис зв'язку",
    relationDescriptionFallback: "Для цього зв'язку ще не додано опис.",
    whatToCheck: "Що перевіряти",
    defaultCheckAction: "Перевірити офіційні сторінки обох інституцій.",
    officialSources: "Офіційні джерела",
    noSpecificSources: "Для цього зв'язку поки не додано окремих джерел.",
    relationEmptyState:
      "Виберіть зв'язок зі списку або натисніть на стрілку на полотні, щоб побачити пояснення.",
    officialSite: "Офіційний сайт",
    verifyPrefix: "Перевірити:",
    verifyFallback: "Перевірити джерело",
  }),
  en: createCopy({
    navEyebrow: "Navigation",
    appTitle: "Country Map",
    pageSwitchAria: "Application views",
    pageSwitchLabel: "View",
    themeSwitchLabel: "Theme",
    languageSwitchLabel: "Language",
    lightTheme: "Light",
    darkTheme: "Dark",
    listTab: "List",
    mindMapTab: "Map",
    projectEyebrow: "Project",
    loadingTitle: "Loading the map",
    loadingDescription:
      "Preparing the structure so you can switch between the list and the visual map.",
    errorTitle: "Could not open the map",
    errorDescription: "Data was not found.",
    aboutProject: "About the project",
    heroTitle: "Country structure map",
    heroText:
      "This project helps you quickly navigate institutions, their roles, and the connections between them. You can find a node, see its place in the hierarchy, and jump to the visual relationship map.",
    searchPlaceholder: "Search",
    searchResultsAria: "Search results",
    nothingFound: "Nothing found.",
    structureEyebrow: "Structure",
    hierarchyTitle: "Hierarchy",
    expandAll: "Expand all",
    collapseAll: "Collapse",
    tryAnotherQuery: "Nothing found. Try another query.",
    nodeCardEyebrow: "Node card",
    breadcrumbAria: "Breadcrumb",
    whatIsThis: "What is it",
    directChildren: "Direct child nodes",
    noChildren: "There are no child elements for this node yet.",
    explanationEyebrow: "Explanation",
    howToReadArrows: "How to read arrows",
    helpTextOne: "An arrow shows the direction of interaction between two nodes.",
    helpTextTwo:
      "The line color and style hint at the connection type: hierarchy, coordination, oversight, service, or legal basis.",
    helpTextThree:
      "Click an arrow to see its explanation and sources for verification.",
    nodesTitle: "Nodes",
    nodesText: "Elements currently displayed on the map.",
    relationsTitle: "Relations",
    relationsText: "Arrows connecting nodes on the canvas.",
    activeNodeTitle: "Active node",
    activeNodeText: "The currently selected element.",
    levelWord: "Level",
    nodesWord: "nodes",
    relationsWord: "relations",
    zoomWord: "Zoom",
    levelOverviewText: "Key objects from this level within the overall structure.",
    mindMapEyebrow: "Relationship map",
    globalMindMap: "Global map",
    zoomOut: "Zoom out",
    zoomIn: "Zoom in",
    enterFullscreen: "Enter fullscreen",
    exitFullscreen: "Exit fullscreen",
    focusActiveNode: "Focus active node",
    relationDetailsEyebrow: "Relation details",
    pickRelation: "Pick a relation",
    activeNodeRelations: "Relations of the active node",
    noVisibleRelations: "There are no visible relations for the active node on the map yet.",
    relationDescription: "Relation description",
    relationDescriptionFallback: "No description has been added for this relation yet.",
    whatToCheck: "What to check",
    defaultCheckAction: "Check the official pages of both institutions.",
    officialSources: "Official sources",
    noSpecificSources: "No dedicated sources have been added for this relation yet.",
    relationEmptyState:
      "Select a relation from the list or click an arrow on the canvas to see its explanation.",
    officialSite: "Official site",
    verifyPrefix: "Verify:",
    verifyFallback: "Verify source",
  }),
};
